/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.hrms.performance;
// Generated Jun 13, 2009 2:06:20 PM by Hibernate Tools 3.2.1.GA

import com.krawler.hrms.master.MasterData;




/**
 * Managecmpt generated by hbm2java
 */
public class Managecmpt  implements java.io.Serializable {


     private String mid;
     private Mastercmpt mastercmpt;
     private MasterData desig;
     private Integer delflag;
     private Integer weightage;

    public MasterData getDesig() {
        return desig;
    }

    public void setDesig(MasterData desig) {
        this.desig = desig;
    }
     //private int desid;

    public Managecmpt() {
    }

    public Managecmpt(String mid, Mastercmpt mastercmpt, MasterData desig, Integer delflag) {
        this.mid = mid;
        this.mastercmpt = mastercmpt;
        this.desig = desig;
        this.delflag=delflag;
    }
    public String getMid() {
        return this.mid;
    }
    
    public void setMid(String mid) {
        this.mid = mid;
    }
    public Mastercmpt getMastercmpt() {
        return this.mastercmpt;
    }
    
    public void setMastercmpt(Mastercmpt mastercmpt) {
        this.mastercmpt = mastercmpt;
    }

    public Integer getDelflag() {
        return delflag;
    }

    public void setDelflag(Integer delflag) {
        this.delflag = delflag;
    }
    public Integer getWeightage() {
        return weightage;
    }
    public void setWeightage(Integer weightage) {
        this.weightage = weightage;
    }    
}

