/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package masterDB;
// Generated Jul 1, 2009 2:58:39 PM by Hibernate Tools 3.2.1.GA


import com.krawler.common.admin.User;
import com.krawler.common.admin.userSalaryTemplateMap;
import java.util.Date;

/**
 * Payhistory generated by hbm2java
 */
public class Payhistory  implements java.io.Serializable {


     private String historyid;
     private User userID;
     private Template template;
     private userSalaryTemplateMap mappingid;
     private String name;
     private String design;
     private String gross;
     private String net;
     private String wagetot;
     private String taxtot;
     private String deductot;//status
     private String ectot;
     private Date paydate;
     private String salary;
     private String wage;
     private String tax;
     private String status;
     private String paymonth;
     private Date paycyclestart;
     private Date paycycleend;
     private Date createdon;
     private Date createdfor;
     private Date generatedon;
     private String department;
     private Double unpaidleaves;
     public static String GENERATED="1";
     private int salarystatus;
    public Payhistory() {
    }

    public Date getPaycycleend() {
        return paycycleend;
    }

    public void setPaycycleend(Date paycycleend) {
        this.paycycleend = paycycleend;
    }

    public userSalaryTemplateMap getMappingid() {
        return mappingid;
    }

    public void setMappingid(userSalaryTemplateMap mappingid) {
        this.mappingid = mappingid;
    }

    public Double getUnpaidleaves() {
        return unpaidleaves;
    }

    public void setUnpaidleaves(Double unpaidleaves) {
        this.unpaidleaves = unpaidleaves;
    }

    public Date getPaycyclestart() {
        return paycyclestart;
    }

    public void setPaycyclestart(Date paycyclestart) {
        this.paycyclestart = paycyclestart;
    }

    public Date getCreatedfor() {
        return createdfor;
    }

    public void setCreatedfor(Date createdfor) {
        this.createdfor = createdfor;
    }

    public Date getCreatedon() {
        return createdon;
    }

    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    public String getDeductot() {
        return deductot;
    }

    public void setDeductot(String deductot) {
        this.deductot = deductot;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDesign() {
        return design;
    }

    public void setDesign(String design) {
        this.design = design;
    }

    public Date getGeneratedon() {
        return generatedon;
    }

    public void setGeneratedon(Date generatedon) {
        this.generatedon = generatedon;
    }

    public String getGross() {
        return gross;
    }

    public void setGross(String gross) {
        this.gross = gross;
    }

    public String getHistoryid() {
        return historyid;
    }

    public void setHistoryid(String historyid) {
        this.historyid = historyid;
    }

    public String getName() {
    	return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNet() {
        return net;
    }

    public void setNet(String net) {
        this.net = net;
    }

    public Date getPaydate() {
        return paydate;
    }

    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    public String getPaymonth() {
        return paymonth;
    }

    public void setPaymonth(String paymonth) {
        this.paymonth = paymonth;
    }

    public String getSalary() {
        return salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTax() {
        return tax;
    }

    public void setTax(String tax) {
        this.tax = tax;
    }

    public String getTaxtot() {
        return taxtot;
    }

    public void setTaxtot(String taxtot) {
        this.taxtot = taxtot;
    }

    public Template getTemplate() {
        return template;
    }

    public void setTemplate(Template template) {
        this.template = template;
    }

    public User getUserID() {
        return userID;
    }

    public void setUserID(User userID) {
        this.userID = userID;
    }

    public String getWage() {
        return wage;
    }

    public void setWage(String wage) {
        this.wage = wage;
    }

    public String getWagetot() {
        return wagetot;
    }

    public void setWagetot(String wagetot) {
        this.wagetot = wagetot;
    }

    public String getEctot() {
        return ectot;
    }

    public void setEctot(String ectot) {
        this.ectot = ectot;
    }

    public int getSalarystatus() {
        return salarystatus;
    }

    public void setSalarystatus(int salarystatus) {
        this.salarystatus = salarystatus;
    }

   
}


