/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package masterDB;
// Generated Jul 1, 2009 2:58:39 PM by Hibernate Tools 3.2.1.GA


import com.krawler.common.admin.Company;
import java.util.HashSet;
import java.util.Set;

/**
 * Wagemaster generated by hbm2java
 */
public class Wagemaster  implements java.io.Serializable {


     private String wageid;
     private Company companydetails;
     private String wagetype;
     private Wagemaster depwageid;
     private Integer rate;
     private String wcode;
     private double  cash;
     private boolean isdefault;
     private Integer computeon;
     private String expr;

    public Wagemaster()
    {
        
    }

    public Wagemaster(String wageid, Company companydetails, String wagetype, Integer rate, String wcode, double cash, boolean isdefault, Wagemaster depwageid) {
        this.wageid = wageid;
        this.companydetails = companydetails;
        this.wagetype = wagetype;
        this.rate = rate;
        this.wcode = wcode;
        this.cash = cash;
        this.isdefault = isdefault;
        this.depwageid = depwageid;
    }

    public Integer getComputeon() {
        return computeon;
    }

    public void setComputeon(Integer computeon) {
        this.computeon = computeon;
    }

    public String getExpr() {
        return expr;
    }

    public void setExpr(String expr) {
        this.expr = expr;
    }

    

    public double getCash() {
        return cash;
    }

    public void setCash(double cash) {
        this.cash = cash;
    }

    public Company getCompanydetails() {
        return companydetails;
    }

    public void setCompanydetails(Company companydetails) {
        this.companydetails = companydetails;
    }

    public boolean isIsdefault() {
        return isdefault;
    }

    public void setIsdefault(boolean isdefault) {
        this.isdefault = isdefault;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public String getWageid() {
        return wageid;
    }

    public void setWageid(String wageid) {
        this.wageid = wageid;
    }

    public Wagemaster getDepwageid() {
        return depwageid;
    }

    public void setDepwageid(Wagemaster depwageid) {
        this.depwageid = depwageid;
    }

    public String getWagetype() {
        return wagetype;
    }

    public void setWagetype(String wagetype) {
        this.wagetype = wagetype;
    }

    public String getWcode() {
        return wcode;
    }

    public void setWcode(String wcode) {
        this.wcode = wcode;
    }

   
}
