/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package masterDB;
// Generated Jul 1, 2009 2:58:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Audittrail generated by hbm2java
 */
public class AudittrailPayroll  implements java.io.Serializable {


     private String id;
     private String typeofwork;
     private String ip;
     private String companyid;
     private String userid;
     private Date date;
	 private String spid;

    public AudittrailPayroll() {
    }

    public AudittrailPayroll(String id, String typeofwork, String ip, String companyid, String userid, Date date,String spid) {
       this.id = id;
       this.typeofwork = typeofwork;
       this.ip = ip;
       this.companyid = companyid;
       this.userid = userid;
	   this.spid=spid;
       this.date = date;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTypeofwork() {
        return this.typeofwork;
    }
    
    public void setTypeofwork(String typeofwork) {
        this.typeofwork = typeofwork;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getCompanyid() {
        return this.companyid;
    }
    
    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
	 public String getSpid() {
        return this.spid;
    }

    public void setSpid(String spid) {
        this.spid = spid;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


