/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package masterDB;
// Generated Jul 1, 2009 2:58:39 PM by Hibernate Tools 3.2.1.GA



/**
 * Historydetail generated by hbm2java
 */
public class Historydetail  implements java.io.Serializable {


     private String primid;
     private Payhistory payhistory;
     private String type;
     private String rate;
     private String amount;
     private String name;
     private Wagemaster wagemaster;
     private Deductionmaster deductionmaster;
     private Taxmaster taxmaster;
     private EmployerContribution employercontributionmaster;

    public Historydetail() {
    }


    public Historydetail(String primid) {
        this.primid = primid;
    }
    public Historydetail(String primid, Payhistory payhistory, String type, String rate, String amount, String name) {
       this.primid = primid;
       this.payhistory = payhistory;
       this.type = type;
       this.rate = rate;
       this.amount = amount;
       this.name = name;
    }

    public String getPrimid() {
        return this.primid;
    }

    public void setPrimid(String primid) {
        this.primid = primid;
    }
    public Payhistory getPayhistory() {
        return this.payhistory;
    }

    public void setPayhistory(Payhistory payhistory) {
        this.payhistory = payhistory;
    }
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
    public String getRate() {
        return this.rate;
    }

    public void setRate(String rate) {
        this.rate = rate;
    }
    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

	public Wagemaster getWagemaster() {
		return wagemaster;
	}

	public void setWagemaster(Wagemaster wagemaster) {
		this.wagemaster = wagemaster;
	}

	public Deductionmaster getDeductionmaster() {
		return deductionmaster;
	}

	public void setDeductionmaster(Deductionmaster deductionmaster) {
		this.deductionmaster = deductionmaster;
	}

	public Taxmaster getTaxmaster() {
		return taxmaster;
	}

	public void setTaxmaster(Taxmaster taxmaster) {
		this.taxmaster = taxmaster;
	}

	public EmployerContribution getEmployercontributionmaster() {
		return employercontributionmaster;
	}

	public void setEmployercontributionmaster(
			EmployerContribution employercontributionmaster) {
		this.employercontributionmaster = employercontributionmaster;
	}
}


