/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package masterDB;

import java.util.HashSet;
import java.util.Set;

/**
 * Template generated by hbm2java
 */
public class TempTemplate implements java.io.Serializable {

	private String templateid;
	private String templatename;
	private String startdate;
	private String enddate;
	private String paymentdate;
	private String startrange;
	private String endrange;
	private String companyid;

	public TempTemplate() {
	}

	public TempTemplate(String templateid,String templatename, String startrange, String endrange) {
		this.templateid = templateid;
		this.templatename = templatename;
		this.startrange = startrange;
		this.endrange = endrange;
	}

	public TempTemplate(String templateid,String templatename, String startdate, String enddate, String paymentdate, String startrange, String endrange, String companyid) {
		this.templateid = templateid;
		this.templatename = templatename;
		this.startdate = startdate;
		this.enddate = enddate;
		this.paymentdate = paymentdate;
		this.startrange = startrange;
		this.endrange = endrange;
		this.companyid = companyid;
	}

	public String getTemplateid() {
		return this.templateid;
	}

	public void setTemplateid(String templateid) {
		this.templateid = templateid;
	}

	public String getTemplatename() {
		return this.templatename;
	}

	public void setTemplatename(String templatename) {
		this.templatename = templatename;
	}

	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public String getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(String paymentdate) {
		this.paymentdate = paymentdate;
	}

	public String getStartrange() {
		return this.startrange;
	}

	public void setStartrange(String startrange) {
		this.startrange = startrange;
	}

	public String getEndrange() {
		return this.endrange;
	}

	public void setEndrange(String endrange) {
		this.endrange = endrange;
	}

	public String getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(String companyid) {
		this.companyid=companyid;
	}
}


